version: "3"
services:
  webserver: 
    hostname: roary
    build:
      context: webserver
    ports:
      - 80:80
      - 443:443
#     volumes:
#       - database:/usr/db

# volumes:
#   database:

