version: "3"
services:
  webserver: 
    hostname: roary
    build:
      context: webserver
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./webserver/data/roary.db:/var/www/data/roary.db:rw

